general:
  buildTool: 'mta'
steps:
  mtaBuild:
    buildTarget: 'CF'
    platform: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cf-deploy'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: 'PreSales_jmr'
      space: 'dev'

